### ISSUE TITLE
Бот-хуебот

### ISSUE THREAD

**Issue by Khavrolev** [orangefrg/rpfti_bot#8]
Здраствуйте. Я, Сергей. Хотел бы чтобы вы сделали бота, бот-хуебот суть такова... Пользователь может писать разные слова. И если пользователь пишет слово, то бот предумывает ему рифму-хуифму. Можно рифмовать корованы... И пользователю раз он в телеграме то сделать так что там была запоминалка крутых рифм... 

P.S. Я джва года хочу такого бота.

**Comment by orangefrg** [comment]
Добавлено в боте «ты будешь рыдать»
